pipeline {
    agent any 
    environment {
    DOCKERHUB_CREDENTIALS = credentials('docker')
    }
    stages { 
        stage('SCM Checkout') {
            steps{
            git url: 'https://github.com/rupalisin/devopsAssignment.git', branch: 'main'
            }
        }
 
        stage('Build docker image') {
            steps {  
                script {
                    dir('devopsAssignment') {
                        sh 'docker build -t singh926/devops:$BUILD_NUMBER .'
                    }
                } 
            }
        }
        stage('login to dockerhub') {
            steps{
                sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
            }
        }
        stage('push image') {
            steps{
                sh 'docker push singh926/devops:$BUILD_NUMBER'
            }
        }
}
post {
        always {
            sh 'docker logout'
        }
    }
}